### ISSUE TITLE
Position 6241, mate in 16?

### ISSUE THREAD

**Issue by Yery** [robertnurnberg/matetools#39]
Stockfish says there is a mate in 16:
8/N6p/b7/8/2p4p/p1P2Q2/Pp1PP1rp/1Rb1K2k w - - bm #21; 00:26 @ C0/R0/K2/P4/X7;

Stockfish dev-20240509-c43425b0 by the Stockfish developers (see AUTHORS file)
info string NNUE evaluation using nn-ae6a388e4a1a.nnue (132MiB, (22528, 3072, 15, 32, 1))
info string NNUE evaluation using nn-baff1ede1f90.nnue (6MiB, (22528, 128, 15, 32, 1))
info string NNUE evaluation using nn-ae6a388e4a1a.nnue (132MiB, (22528, 3072, 15, 32, 1))
info string NNUE evaluation using nn-baff1ede1f90.nnue (6MiB, (22528, 128, 15, 32, 1))
....
info depth 72 seldepth 42 multipv 1 score mate 16 nodes 2263492775 nps 16124959 hashfull 48 tbhits 0 time 140372 pv e1f1 h4h3 f3c6 h7h6 c6a8 c1d2 a7c8 a6c8 a8c8 d2e3 c8c6 e3f2 c6f3 f2h4 e2e4 h4g3 e4e5 g3h4 e5e6 h6h5 e6e7 h4e7 f3h3 g2g1 f1f2 e7c5 f2f3 g1f1 b1f1 c5g1 h3g2

**Comment by robertnurnberg** [comment]
Confirmed locally. Thanks a lot! Will update here and open PR for matetrack.

**Comment by robertnurnberg** [comment]
Completed in https://github.com/robertnurnberg/matetools/commit/db749b9eef84be9fcf1adcf60ce997aa31e99c7a.

**Comment by Yery** [comment]
Great, thanks!
