### ISSUE TITLE
Position 6555 mate in 55

### ISSUE THREAD

**Issue by Yery** [robertnurnberg/matetools#54]
Q1b4q/2Pp2p1/3P1k1b/6pP/3p1pPp/3P1pBK/5P2/8 w - - bm #125;
This is indeed a mate in at most 55, confirming https://talkchess.com/viewtopic.php?p=961105#p961105 
In fact, the first 21 moves are identical (after that multiple equivalent lines exist).
Analysis was carried out with The Huntsman 1 as downloaded from ipman chess. 

Here is the analysis. All moves of black are forced, or are split up for the hardest side lines. The mainline is without letters.

1.   a8e4   f6f7 (forced)
2.   e4e7   f7g8 (forced)
3.   e7e8   g8h7 (forced)
4.   e8g6   h7g8 (forced)
5.   g3h4   g5h4 (the other moves are M19 or worse)
6.   h3h4   g8f8 (the other moves are M26 or worse)
7.   g4g5   h6g5 (the other moves are M27 or worse)
8.   g6g5       

Now 10 possible black moves, 7 are M13 or worse, 3 remaining

8a.  ...    f8f7   2b4q/2Pp1kp1/3P4/6QP/3p1p1K/3P1p2/5P2/8 w - - 1 9 
info depth 70 seldepth 78 multipv 1 score mate 41 nodes 139313789846 nps 62813207 hashfull 724 tbhits 0 time 2217906 pv g5e7 f7g8 e7e8 g8h7 e8g6 h7g8 h4g4 g8f8 g4f3 h8g8 g6f5 f8e8 f5g5 g8e6 g5g7 c8a6 f3f4 e6d6 g7e5 d6e6 h5h6 e6e5 f4e5 e8f7 f2f4 d7d6 e5d6 a6c8 h6h7 f7g7 d6e7 c8g4 e7d8 g7h7 c7c8q g4c8 d8c8 h7g6 c8b7 g6f5 b7c6 f5f4 c6d5 f4f5 d5d4 f5e6 d4c5 e6d7 c5d5 d7e7 d5c6 e7f7 c6d6 f7f6 d3d4 f6f7 d4d5 f7f6 d6c6 f6g5 d5d6 g5f6 d6d7 f6e7 c6c7 e7e6 d7d8q e6f5 d8h4 f5e5 c7c6 e5f5 c6d6 f5g6 d6e6 g6g7 h4g3 g7h6 e6f6 h6h7 g3g7 

8b.  ...    h8h6  
9b.  g5d8   f8f7 (forced)      
10b. d8c8         2Q5/2Pp1kp1/3P3q/7P/3p1p1K/3P1p2/5P2/8 b - - 0 10  
info depth 61 seldepth 73 multipv 1 score mate -37 nodes 382273930786 nps 52954793 hashfull 980 tbhits 0 time 7218873 pv h6f6 h4g4 f6e6 g4f3 e6h3 f3e4 h3h1 e4e5 h1e1 e5f5 e1e6 f5f4 e6d6 f4e4 d6e7 e4d5 e7e6 d5d4 e6b6 d4c4 d7d5 c4d5 b6b5 d5e4 b5c6 e4e3 c6c1 e3d4 c1b2 d4c4 b2c2 c4b5 c2b3 b5a6 b3a3 a6b7 a3b3 b7a7 b3d3 a7b8 d3d6 f2f3 f7e7 c8b7 e7f8 b7b3 f8e7 b8b7 d6d7 b3b4 e7f7 b7b8 f7f6 c7c8q d7c8 b8c8 f6e5 f3f4 e5f5 b4f8 f5e4 f8g7 e4d3 h5h6 d3e2 h6h7 e2f3 h7h8q f3e4 h8d8   

8.   ...    f8g8  
9.   h4g4    

Now 9 possible replies, 5 are M16 or worse, 4 remaining
	
9c.  ...    g8f7  2b4q/2Pp1kp1/3P4/6QP/3p1pK1/3P1p2/5P2/8 w - - 3 10 
info depth 75 seldepth 80 multipv 1 score mate 38 nodes 1679894123661 nps 82291030 hashfull 913 tbhits 0 time 20414061 pv g5e7 f7g8 e7e8 g8h7 e8g6 h7g8 g4f3 g8f8 g6g5 f8f7 g5e7 f7g8 e7d8 g8h7 f3f4 h8g8 d8g8 h7g8 f4e4 g8f7 e4e5 c8a6 e5d4 f7e6 d4c5 e6e5 d3d4 e5e4 c5b6 a6c8 b6a7 e4d5 a7b8 c8a6 c7c8q a6c8 b8c8 d5d6 f2f4 d6e7 f4f5 d7d5 c8c7 e7f7 c7c6 f7f6 c6d5 f6f5 d5c6 f5g4 d4d5 g4h5 d5d6 h5g5 d6d7 g5f4 d7d8q f4f5 d8f8 f5g4 f8g7 g4f3 c6d5 f3f4 g7c3 f4g5 c3e5 g5g6 d5e6 g6h7 e5g3 h7h8 e6f6 h8h7 g3g7

9d.  ...    c8b7  6kq/1bPp2p1/3P4/6QP/3p1pK1/3P1p2/5P2/8 w - - 3 10   
info depth 81 seldepth 78 multipv 1 score mate 36 nodes 6546896665702 nps 106775526 hashfull 994 tbhits 0 time 61314581 pv g5g6 b7c8 g4f3 g8f8 g6g5 f8f7 g5e7 f7g8 e7d8 g8h7 f3f4 h8g8 d8g8 h7g8 f4e5 g8h7 e5d4 g7g6 h5g6 h7g6 d4c5 g6f5 c5b6 f5e6 b6a7 e6d6 a7b8 c8a6 c7c8q a6c8 b8c8 d6c6 f2f4 c6d6 c8d8 d6e6 d3d4 d7d5 d8c7 e6f5 c7d6 f5e4 d6c5 e4f4 c5d5 f4f5 d5c6 f5f6 d4d5 f6g6 d5d6 g6f6 d6d7 f6e7 c6c7 e7e6 d7d8q e6f5 d8d3 f5g4 c7d6 g4g5 d6e5 g5g4 d3e2 g4g5 e2g2 g5h5 e5f5 h5h4 g2h2

9e.  ...    g8h7  2b4q/2Pp2pk/3P4/6QP/3p1pK1/3P1p2/5P2/8 w - - 3 10 
info depth 79 seldepth 68 multipv 1 score mate 34 nodes 128466894332 nps 55274215 hashfull 787 tbhits 0 time 2324174 pv g5g6 h7g8 g4f3 g8f8 f3f4 f8g8 g6e8 g8h7 e8h8 h7h8 f4e4 h8h7 e4d4 g7g6 h5g6 h7g6 d4c5 g6f5 c5b6 f5e5 b6a7 e5d6 a7b8 c8a6 c7c8q a6c8 b8c8 d6c6 c8d8 c6d6 f2f4 d6e6 d3d4 d7d5 d8c7 e6f5 c7d6 f5e4 d6c5 e4f4 c5d5 f4f5 d5c6 f5f4 d4d5 f4e5 d5d6 e5f6 d6d7 f6e7 c6c7 e7e6 d7d8q e6f5 d8d3 f5g4 c7d6 g4h4 d6e5 h4g4 d3e2 g4h4 e2g2 h4h5 e5f5 h5h4 g2h2

9.   ...    h8h6   2b3k1/2Pp2p1/3P3q/6QP/3p1pK1/3P1p2/5P2/8 w - - 3 10 
info depth 83 seldepth 92 multipv 1 score mate 46 nodes 1609653632848 nps 53729601 hashfull 1000 tbhits 0 time 29958414 pv g5d8 g8h7 d8c8 h6e6 g4f3 e6h3 f3e4 h3h1 e4e5 h1e1 e5f5 e1e6 f5f4 e6d6 f4e4 d6e7 e4d5 e7e6 d5d4 e6f5 f2f4 f5f4 d4c5 f4e3 c5b5 e3d3 b5b6 d3d4 b6b7 d4b4 b7a8 b4a5 a8b8 a5h5 c8b7 h5e5 b7b4 h7h8 b8b7 e5d5 b7a7 d5a2 a7b8 a2h2 b4f8 h8h7 f8f5 h7h8 f5g5 h8g8 g5d5 g8f8 d5c4 f8e7 b8b7 h2h1 b7a6 h1a1 a6b5 e7f6 c7c8q a1b2 b5a6 b2a3 a6b6 a3b2 c4b5 b2b5 b6b5 f6e7 c8g8 e7f6 g8d5 g7g5 d5d7 f6e5 d7g4 e5d5 g4g5 d5d4 g5g4 d4d3 b5b4 d3d2 g4e4 d2c1 b4c3 c1d1 e4e8 d1c1 e8e1

Full line:
a8e4 f6f7 e4e7 f7g8 e7e8 g8h7 e8g6 h7g8 g3h4 g5h4 h3h4 g8f8 g4g5 h6g5 g6g5 f8g8 h4g4 h8h6 g5d8 g8h7 d8c8 h6e6 g4f3 e6h3 f3e4 h3h1 e4e5 h1e1 e5f5 e1e6 f5f4 e6d6 f4e4 d6e7 e4d5 e7e6 d5d4 e6f5 f2f4 f5f4 d4c5 f4e3 c5b5 e3d3 b5b6 d3d4 b6b7 d4b4 b7a8 b4a5 a8b8 a5h5 c8b7 h5e5 b7b4 h7h8 b8b7 e5d5 b7a7 d5a2 a7b8 a2h2 b4f8 h8h7 f8f5 h7h8 f5g5 h8g8 g5d5 g8f8 d5c4 f8e7 b8b7 h2h1 b7a6 h1a1 a6b5 e7f6 c7c8q a1b2 b5a6 b2a3 a6b6 a3b2 c4b5 b2b5 b6b5 f6e7 c8g8 e7f6 g8d5 g7g5 d5d7 f6e5 d7g4 e5d5 g4g5 d5d4 g5g4 d4d3 b5b4 d3d2 g4e4 d2c1 b4c3 c1d1 e4e8 d1c1 e8e1

**Comment by robertnurnberg** [comment]
I'm impressed. Will merge the PV this weekend. Thanks a lot.
