### ISSUE TITLE
Position 8/p1p3Pr/p1p2P2/7p/7k/6p1/p1p3P1/rbK5 w - -  mate in 63?!

### ISSUE THREAD

**Issue by Yery** [robertnurnberg/matetools#61]
A particular pattern can be repeated over and over for black, giving easily the mate in 66. However, at one moment in the PV, black's pawns are such that white can deviate from the pattern, saving 2 moves and given the mate in 64. However, it appears there is another one of these moments, saving another move, thus yielding a mate in 63. PVs for both the mates in 64 and 63 are given below. 

8/p1p3Pr/p1p2P2/7p/7k/6p1/p1p3P1/rbK5 w - - 0 1 

1.  f6f7   h7g7 (forced, rest is M5)
2.  f7f8q  

Three viable options for black (rest is M21 or shorter)

2a.  ...   g7g4  option 1 
3a. f8f6   g4g5  forced, this transposes to move 5 below, showing this is not blacks optimal defence

2b.  ...   g7g5  option 2
3b.  f8f4  g5g4  forced, this transposes to move 4 below

2.  ...    g7g6  option 3
3.  f8f4   g6g4  forced
4.  f4f6   g4g5  forced
5.  f6e7           

Black has to move a pawn, after which The Huntsman can find a mate in 59. Note that The Huntsman often truncates PVs, in the cases below 10 moves or so short, I completed these afterwards.
                    
5.  ...    a6a5     8/p1p1Q3/2p5/p5rp/7k/6p1/p1p3P1/rbK5 w - - 0 6 
info depth 69 seldepth 91 multipv 1 score mate 59 nodes 18244140356 nps 60813598 hashfull 170 tbhits 0 time 300001 pv e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a7a6 e7f7 h4g4 f7f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a5a4 e7f7 h4g4 f7f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a6a5 e7f7 h4g4 f7f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a4a3 e7f7 h4g4 f7f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a5a4 e7f8 h4g4 f8f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c6c5 e7e6 g5g7 e6f6 g7g5 f6e7 c7c6 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c5c4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c6c5 e7f7 h4g4 f7f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c4c3 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c5c4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 h4g4 e7e4    
 
5.  ...    c6c5     8/p1p1Q3/p7/2p3rp/7k/6p1/p1p3P1/rbK5 w - - 0 6 
info depth 70 seldepth 96 multipv 1 score mate 59 nodes 37546920931 nps 62578097 hashfull 297 tbhits 0 time 600001 pv e7e6 g5g4 e6f6 g4g5 f6e7 c7c6 e7f7 h4g4 f7f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a6a5 e7f8 h4g4 f8f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a5a4 e7f8 h4g4 f8f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c5c4 e7e4 g5g4 e4e5 g4g6 e5f4 g6g4 f4f6 g4g5 f6e7 c4c3 e7e4 g5g4 e4e5 g4g6 e5f4 g6g4 f4f6 g4g5 f6e7 a7a6 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a4a3 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a6a5 e7f7 h4g4 f7f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a5a4 e7f8 h4g4 f8f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c6c5 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c5c4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 h4g4 e7e4

So this gives the PVs for the mate in 64.  Note that this is the usual pattern for white: e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7
With the exception after first black pawn move to c6c5: e7e6 g5g4 e6f6 g4g5 f6e7  . These will be reused below.
For the mate in 63, at some point black must have pawns on c6 and c4. There are 10 possible pawn configurations for the a pawns (a7/a6, a7/a5, a7/a4, a7/a3, a6/a5, a6/a4, a6/a3, a5/a4, a5/a3, a4/a3) in which this can happen. In all cases, once black pawns are on c6 and c4, we play e7e4 g5g4 and then let the huntsman find the mate. Note that variation 1-9 all have very similar lines. However, variation 10 apparently allows a long black king-walk, and is an extremely hard to find mate in 19.

Variation 1 (a7/a6, 14 first moves are forced)
f6f7 h7g7 f7f8q g7g6 f8f4 g6g4 f4f6 g4g5 f6e7 c6c5 e7e6 g5g4 e6f6 g4g5 f6e7 c7c6 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c5c4 e7e4 g5g4
8/p7/p1p5/7p/2p1Q1rk/6p1/p1p3P1/rbK5 w - - 2 15 
info depth 79 seldepth 97 multipv 1 score mate 49 nodes 31475103629 nps 58574133 hashfull 309 tbhits 0 time 537355 pv e4f5 g4g7 f5f6 g7g5 f6e7 c4c3 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a6a5 e7f7 h4g4 f7f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a5a4 e7e4 g5g4 e4e5 g4g6 e5f4 g6g4 f4f6 g4g5 f6e7 a7a6 e7e4 g5g4 e4e5 g4g6 e5f4 g6g4 f4f6 g4g5 f6e7 a6a5 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a4a3 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c6c5 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c5c4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a5a4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 h4g4 e7e4

Variation 2 (a7/a5, first 19 moves forced)
f6f7 h7g7 f7f8q g7g6 f8f4 g6g4 f4f6 g4g5 f6e7 a6a5 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c6c5 e7e6 g5g4 e6f6 g4g5 f6e7 c7c6 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c5c4 e7e4 g5g4
8/p7/2p5/p6p/2p1Q1rk/6p1/p1p3P1/rbK5 w - - 2 20 
info depth 73 seldepth 90 multipv 1 score mate 44 nodes 15273823608 nps 59322270 hashfull 157 tbhits 0 time 257472 pv e4f5 g4g7 f5f6 g7g5 f6e7 c4c3 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a7a6 e7f7 h4g4 f7f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a5a4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a4a3 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a6a5 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c6c5 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c5c4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a5a4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 h4g4 e7e4

Variation 3 (a7/a4, first 24 moves forced)
f6f7 h7g7 f7f8q g7g6 f8f4 g6g4 f4f6 g4g5 f6e7 a6a5 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c6c5 e7e6 g5g4 e6f6 g4g5 f6e7 c7c6 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a5a4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c5c4 e7e4 g5g4
8/p7/2p5/7p/p1p1Q1rk/6p1/p1p3P1/rbK5 w - - 2 25 
info depth 63 seldepth 77 multipv 1 score mate 39 nodes 5684327787 nps 57888159 hashfull 74 tbhits 0 time 98195 pv e4f5 g4g7 f5f6 g7g5 f6e7 c4c3 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a4a3 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a7a6 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a6a5 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a5a4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c6c5 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c5c4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 h4g4 e7e4

Variation 4 (a7/a3, first 29 moves forced)
f6f7 h7g7 f7f8q g7g6 f8f4 g6g4 f4f6 g4g5 f6e7 a6a5 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c6c5 e7e6 g5g4 e6f6 g4g5 f6e7 c7c6 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a5a4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a4a3 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c5c4 e7e4 g5g4
8/p7/2p5/7p/2p1Q1rk/p5p1/p1p3P1/rbK5 w - - 2 30 
info depth 58 seldepth 70 multipv 1 score mate 34 nodes 4200838337 nps 61190327 hashfull 43 tbhits 0 time 68652 pv e4f5 g4g7 f5f6 g7g5 f6e7 c4c3 e7f8 h4g4 f8f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a7a6 e7f7 h4g4 f7f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a6a5 e7f7 h4g4 f7f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a5a4 e7f8 h4g4 f8f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c6c5 e7f8 h4g4 f8f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c5c4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 h4g4 e7e4

Variation 5 (a6/a5, first 24 moves forced)
f6f7 h7g7 f7f8q g7g6 f8f4 g6g4 f4f6 g4g5 f6e7 a6a5 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c6c5 e7e6 g5g4 e6f6 g4g5 f6e7 c7c6 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a7a6 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c5c4 e7e4 g5g4
8/8/p1p5/p6p/2p1Q1rk/6p1/p1p3P1/rbK5 w - - 2 25 
info depth 65 seldepth 77 multipv 1 score mate 39 nodes 5624087583 nps 55619604 hashfull 84 tbhits 0 time 101117 pv e4f5 g4g7 f5f6 g7g5 f6e7 c4c3 e7f7 h4g4 f7f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a5a4 e7e4 g5g4 e4e5 g4g6 e5f5 g6g7 f5f6 g7g5 f6e7 a6a5 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a4a3 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a5a4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c6c5 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c5c4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 h4g4 e7e4

Variation 6 (a6/a4, first 29 moves forced)
f6f7 h7g7 f7f8q g7g6 f8f4 g6g4 f4f6 g4g5 f6e7 a6a5 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c6c5 e7e6 g5g4 e6f6 g4g5 f6e7 c7c6 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a7a6 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a5a4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c5c4 e7e4 g5g4 
8/8/p1p5/7p/p1p1Q1rk/6p1/p1p3P1/rbK5 w - - 2 30 
info depth 59 seldepth 70 multipv 1 score mate 34 nodes 4602269313 nps 59710021 hashfull 61 tbhits 0 time 77077 pv e4f5 g4g7 f5f6 g7g5 f6e7 c4c3 e7f7 h4g4 f7f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a6a5 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a4a3 e7f7 h4g4 f7f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a5a4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c6c5 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c5c4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 h4g4 e7e4

Variation 7 (a6/a3, first 34 moves forced)
f6f7 h7g7 f7f8q g7g6 f8f4 g6g4 f4f6 g4g5 f6e7 a6a5 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c6c5 e7e6 g5g4 e6f6 g4g5 f6e7 c7c6 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a7a6 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a5a4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a4a3 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c5c4 e7e4 g5g4 
8/8/p1p5/7p/2p1Q1rk/p5p1/p1p3P1/rbK5 w - - 2 35 
info depth 56 seldepth 64 multipv 1 score mate 29 nodes 1725297753 nps 56275613 hashfull 28 tbhits 0 time 30658 pv e4f5 g4g7 f5f6 g7g5 f6e7 c4c3 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a6a5 e7f7 h4g4 f7f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a5a4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c6c5 e7f7 h4g4 f7f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c5c4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 h4g4 e7e4

Variation 8 (a5/a4, first 34 moves forced)
f6f7 h7g7 f7f8q g7g6 f8f4 g6g4 f4f6 g4g5 f6e7 a6a5 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c6c5 e7e6 g5g4 e6f6 g4g5 f6e7 c7c6 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a7a6 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a5a4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a6a5 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c5c4 e7e4 g5g4
8/8/2p5/p6p/p1p1Q1rk/6p1/p1p3P1/rbK5 w - - 2 35 
info depth 60 seldepth 60 multipv 1 score mate 29 nodes 3226189364 nps 61399767 hashfull 41 tbhits 0 time 52544 pv e4f5 g4g8 f5f6 g8g5 f6e7 a4a3 e7e4 g5g4 e4f5 g4g8 f5f4 g8g4 f4f6 g4g5 f6e7 c4c3 e7f7 h4g4 f7f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c6c5 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c5c4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a5a4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 h4g4 e7e4

Variation 9 (a5/a3, first 39 moves forced)
f6f7 h7g7 f7f8q g7g6 f8f4 g6g4 f4f6 g4g5 f6e7 a6a5 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c6c5 e7e6 g5g4 e6f6 g4g5 f6e7 c7c6 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a7a6 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a5a4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a6a5 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a4a3 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c5c4 e7e4 g5g4
8/8/2p5/p6p/2p1Q1rk/p5p1/p1p3P1/rbK5 w - - 2 40 
info depth 69 seldepth 48 multipv 1 score mate 24 nodes 2838540337 nps 58906766 hashfull 38 tbhits 0 time 48187 pv e4f5 g4g8 f5f6 g8g5 f6e7 a5a4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c6c5 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c4c3 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c5c4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 h4g4 e7e4

Variation 10 (a4/a3, first 44 moves forced)
f6f7 h7g7 f7f8q g7g6 f8f4 g6g4 f4f6 g4g5 f6e7 a6a5 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c6c5 e7e6 g5g4 e6f6 g4g5 f6e7 c7c6 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a7a6 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a5a4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a6a5 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a4a3 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a5a4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c5c4 e7e4 g5g4
8/8/2p5/7p/p1p1Q1rk/p5p1/p1p3P1/rbK5 w - - 2 45 
info depth 73 seldepth 40 multipv 1 score mate 19 nodes 4794996805 nps 27605365 hashfull 117 tbhits 0 time 173698 pv e4f5 g4g8 f5h3 h4g5 h3g3 g5f5 g3g8 f5f4 g8f7 f4g4 f7g6 g4h4 g6f5 h4g3 f5h3 g3f2 h3h2 f2f1 g2g3 c4c3 h2h5 f1g2 g3g4 g2f2 g4g5 f2e3 g5g6 e3f2 g6g7 f2e3 h5e5 e3f2 g7g8q c6c5 e5g3 f2f1 g8c4

For the PV I would suggest variation 10, since it is the hardest to find:
f6f7 h7g7 f7f8q g7g6 f8f4 g6g4 f4f6 g4g5 f6e7 a6a5 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c6c5 e7e6 g5g4 e6f6 g4g5 f6e7 c7c6 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a7a6 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a5a4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a6a5 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a4a3 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a5a4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c5c4 e7e4 g5g4 e4f5 g4g8 f5h3 h4g5 h3g3 g5f5 g3g8 f5f4 g8f7 f4g4 f7g6 g4h4 g6f5 h4g3 f5h3 g3f2 h3h2 f2f1 g2g3 c4c3 h2h5 f1g2 g3g4 g2f2 g4g5 f2e3 g5g6 e3f2 g6g7 f2e3 h5e5 e3f2 g7g8q c6c5 e5g3 f2f1 g8c4

Hope I didn't make any mistakes!

**Comment by robertnurnberg** [comment]
Thanks a lot! So M64 seems to be clear-cut.

What is less obvious to me is how much "human logic" went into the M63 explanation, so how much chance is there that you missed some weird corner case? (Say in one variation black is not forced to move the c pawns, because there is a long king walk escaping repeated checks, which brings that mate distance to >= 64).

Could I also ask @dav1312 for a second opinion on the M63?

I was thinking a nice (but weak) confirmation would be to get [chessdb.cn](https://www.chessdb.cn/queryc_en) to display the M63 as well. The site is down atm, but once back up we can try to use `cdbbulksearch.py` from [cdbexplore](https://github.com/vondele/cdbexplore) with the lines above, plus manual exploration, to make this happen.

**Comment by Yery** [comment]
Thanks I fully agree, M64 is clear-cut, and for M63, there is a non-negligible possibility of error.

**Comment by Yery** [comment]
Uh, I just realized that the premise " must have pawns on c6 and c4 " is wrong. Black can simply walk first the c pawn all the way to c3...  So we can forget about the M63!

**Comment by robertnurnberg** [comment]
Good catch, it was too good to be true. ;) Will prepare a PR to matetrack for the M64 later today. Well done once again!

**Comment by robertnurnberg** [comment]
> Three viable options for black (rest is M21 or shorter)

Could you post here the mate lines for the alternative moves Rf7 Kg5 Kg4?

**Comment by Yery** [comment]
Sure, so for this position: 5Q2/p1p3r1/p1p5/7p/7k/6p1/p1p3P1/rbK5 b - - 0 2

After a longer calculation, there are shorter mates than M21 for these, again with The Huntsman:

info depth 59 seldepth 33 multipv 4 score mate -16 nodes 13631627686 nps 57200040 hashfull 158 tbhits 0 time 238315 pv g7f7 f8f7 h4g5 f7g7 g5f5 g7h6 f5g4 h6g6 g4f4 g6h5 f4e4 h5f3 e4e5 f3g3 e5e4 g3f3 e4d4 g2g4 d4c4 g4g5 c6c5 g5g6 c4b5 g6g7 c5c4 g7g8q b5c5 g8f8 c5d4 f8e7 a6a5 e7e3
info depth 59 seldepth 31 multipv 5 score mate -15 nodes 13631627686 nps 57200040 hashfull 158 tbhits 0 time 238315 pv h4g5 f8g7 g5f5 g7h6 f5g4 h6g6 g4f4 g6h5 f4e4 h5f3 e4e5 f3g3 e5e4 g3f3 e4d4 g2g4 d4c4 g4g5 c6c5 g5g6 c4b5 g6g7 c5c4 g7g8q b5c5 g8f8 c5d4 f8e7 a6a5 e7e3
info depth 59 seldepth 31 multipv 6 score mate -15 nodes 13631627686 nps 57200040 hashfull 158 tbhits 0 time 238315 pv h4g4 f8g7 g4f5 g7h6 f5g4 h6g6 g4f4 g6h5 f4e4 h5f3 e4e5 f3g3 e5e4 g3f3 e4d4 g2g4 d4c4 g4g5 c6c5 g5g6 c4b5 g6g7 c5c4 g7g8q b5c5 g8f8 c5d4 f8e7 a6a5 e7e3

**Comment by robertnurnberg** [comment]
Excellent, thanks a lot. Could you run a long Huntsman analysis on the root position of
```
5Q2/p1p5/p1p5/6rp/7k/6p1/p1p3P1/rbK5 w - - bm #62
```
I have the feeling that this can be shortened, similarly to your analysis above. (The current PV always uses four moves by white for any pawn push by black, but I think you found out that in some cases white needs only two moves?)

**Comment by Yery** [comment]
I am not sure whether I understand. The two PVs of mate in 59, do have the shortcut after the c6c5 move (which reduces the M66 to M64)

in the first line: c6c5 e7e6 g5g7 e6f6 g7g5 f6e7 c7c6  (near the end)
in the second line:  c6c5 e7e6 g5g4 e6f6 g4g5 f6e7 c7c6 (at the start)

or do you mean something else? I did run a very long analysis from the starting position, and was unable to find anything shorter.

**Comment by robertnurnberg** [comment]
This is for a sister position in the epd file. First move is Qe7, and then the pattern we know.

Currently known shortest mate for it is M62, but I think the known PV does not have the shortcut.

**Comment by Yery** [comment]
Ah I see, thanks, I'll start the analysis!

**Comment by Yery** [comment]
You are right!, is a mate in 60:

info depth 66 seldepth 87 multipv 1 score mate 60 nodes 9657651808 nps 57548023 hashfull 80 tbhits 0 time 167819 pv f8e7 a6a5 e7f8 h4g4 f8f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a5a4 e7e4 g5g4 e4e5 g4g6 e5f4 g6g4 f4f6 g4g5 f6e7 a7a6 e7e4 g5g4 e4e5 g4g6 e5f4 g6g4 f4f6 g4g5 f6e7 a6a5 e7f8 h4g4 f8f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a4a3 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a5a4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c6c5 e7e6 g5g7 e6f6 g7g5 f6e7 c5c4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c4c3 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7

PV stops at position (in this particular analysis, The Huntsman loses the mate annoyingly - it is a known problem with that engine). To complete the PV: 

8/2p1Q3/8/6rp/p6k/p1p3p1/p1p3P1/rbK5 b - - 9 44 

info depth 71 seldepth 33 multipv 1 score mate -16 nodes 627118332 nps 59600677 hashfull 3 tbhits 0 time 10522 pv c7c6 e7f8 h4g4 f8f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c6c5 e7f8 h4g4 f8f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c5c4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 h4g4 e7e4

Combining both gives for the full PV:

f8e7 a6a5 e7f8 h4g4 f8f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a5a4 e7e4 g5g4 e4e5 g4g6 e5f4 g6g4 f4f6 g4g5 f6e7 a7a6 e7e4 g5g4 e4e5 g4g6 e5f4 g6g4 f4f6 g4g5 f6e7 a6a5 e7f8 h4g4 f8f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a4a3 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 a5a4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c6c5 e7e6 g5g7 e6f6 g7g5 f6e7 c5c4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c4c3 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c7c6 e7f8 h4g4 f8f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c6c5 e7f8 h4g4 f8f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 c5c4 e7f6 h4g4 f6f3 g4h4 f3f4 g5g4 f4f6 g4g5 f6e7 h4g4 e7e4

**Comment by robertnurnberg** [comment]
Nice, thanks a lot. I have tools in this repo to complete incomplete PVs, so I know that this used to be an issue. Latest stockfish will always have complete mate PVs, but is probably not quite as good as Huntsman to actually find the mates.
